name: Chrome

on: push

jobs:
  chrome:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        containers: [1, 2, 3,4,5,6,7,8,9,10]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Chrome
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          record: true
          parallel: true
          group: 'Actions example'
        env:
          CYPRESS_RECORD_KEY: 524a247d-12cb-443b-89d8-8a4e353084ab
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 10
