name: Chrome

on: push

jobs:
  chrome:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Chrome
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          spec: cypress/e2e/firstAPICall.cy.js
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 10
